[workspace]
name = "sp26-google-gke-social-media"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -v -e ."

geodata-all = "python -m sp26_gke.geodata.cli run-all"
geodata-download-pois = "python -m sp26_gke.geodata.cli download-pois"
geodata-download-census = "python -m sp26_gke.geodata.cli download-census"
geodata-preprocess = "python -m sp26_gke.geodata.cli preprocess"

geodata-plot = "python sp26_gke/plotting/geodata/generate_figures.py"
gke-dummy-job = "python -m sp26_gke.workflows.gke_dummy_job"
sentiment-agent = "python -m sp26_gke.workflows.sentiment_agent"

[dependencies]
python = ">=3.12,<3.14"
pip = "*"

[feature.py_utilities.dependencies]
typer = "*"
colorama = "*"
tqdm = "*"
python-dotenv = "*"
pyyaml = "*"
structlog = "*"
pydantic = ">=2"

[feature.py_data_processing.dependencies]
pyarrow = "*"
pandas = "*"
polars = "*"
numpy = "*"


[feature.py_ml.dependencies]
pytorch = ">=2.1.0"
torchvision = ">=0.16.0"
scikit-learn = "*"
scipy = "*"

[feature.py_plotting.dependencies]
matplotlib = "*"
seaborn = "*"
plotly = "*"


[feature.py_dev.dependencies]
ipython = "*"
ipykernel = "*"
nbconvert = "*"

[feature.py_test.dependencies]
mypy = ">=1.13"
pytest = ">=6"
pytest-cov = "*"

[feature.py_test.tasks]
test = "pytest tests/"

[feature.py_lint.dependencies]
docformatter = "*"
pre-commit = "*"
pre-commit-hooks = "*"
prettier = "*"
ruff = "*"
taplo = "*"
typos = "*"

[feature.py_lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.py_agents.pypi-dependencies]
langgraph = ">=0.2"
langchain-openai = ">=0.3"
tavily-python = ">=0.5"
redis = ">=5.0"
kubernetes = ">=31.0"

[feature.infra.dependencies]
google-cloud-sdk = "*"
terraform = "*"
go-sops = "*"
age = "*"
kubernetes-client = "*"

[environments]
default = { features = [
  "infra",
  "py_utilities",
  "py_data_processing",
  "py_ml",
  "py_plotting",
  "py_dev",
  "py_test",
  "py_lint",
  "py_agents",
] }
lint = { features = ["py_lint"], no-default-feature = true }
infra = { features = ["infra"], no-default-feature = true }
frontend = { features = ["frontend"], no-default-feature = true }

[feature.frontend.dependencies]
nodejs = "*"

[feature.frontend.tasks]
dev = "npm run dev"
